-- Add reference variants without overwriting owner-managed products.
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'civic-eg','HH-HW-000001','1992 Honda Civic EG','Hot Wheels','58th Anniversary: thân xanh, họa tiết Hot Wheels vàng, mâm vàng, card 2/6. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/civic-eg.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='civic-eg' OR upper(sku)='HH-HW-000001' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('1992 Honda Civic EG'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'honda-del-sol','HH-HW-000002','1994 Honda del Sol','Hot Wheels','Premium Fast & Furious: xe trắng, mâm bạc, đóng vỉ, card 3/5. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/honda-del-sol.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='honda-del-sol' OR upper(sku)='HH-HW-000002' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('1994 Honda del Sol'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'ferrari-dino-206','HH-HW-000003','Ferrari Dino 206 GT','Hot Wheels','Ferrari Dino 206 GT màu đỏ, mâm bạc, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-dino-206.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='ferrari-dino-206' OR upper(sku)='HH-HW-000003' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Ferrari Dino 206 GT'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'ferrari-12cilindri','HH-HW-000004','Ferrari 12Cilindri','Hot Wheels','Ferrari 12Cilindri màu xanh, nóc đen, mâm đen trắng, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-12cilindri.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='ferrari-12cilindri' OR upper(sku)='HH-HW-000004' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Ferrari 12Cilindri'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'ferrari-f2004','HH-HW-000005','Ferrari F2004','Hot Wheels','HW Starting Grid: xe đua Ferrari F2004 màu đỏ, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-f2004.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='ferrari-f2004' OR upper(sku)='HH-HW-000005' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Ferrari F2004'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'racing-bulls-f1','HH-HW-000006','Visa Cash App Racing Bulls F1','Hot Wheels','Formula 1: xe trắng xanh, viền mâm xanh, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/racing-bulls-f1.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='racing-bulls-f1' OR upper(sku)='HH-HW-000006' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Visa Cash App Racing Bulls F1'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'porsche-rally','HH-MB-000007','1985 Porsche 911 Rally','Matchbox','Mẫu tham khảo: màu xám, phụ kiện trên nóc, đóng vỉ. Ảnh đang cập nhật.','',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='porsche-rally' OR upper(sku)='HH-MB-000007' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('1985 Porsche 911 Rally'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'porsche-918','HH-MB-000008','Porsche 918 Spyder','Matchbox','Mẫu tham khảo: màu xanh, đóng vỉ. Ảnh đang cập nhật.','',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='porsche-918' OR upper(sku)='HH-MB-000008' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('Porsche 918 Spyder'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'mercedes-500-sel','HH-HW-000009','Mercedes-Benz 500 SEL Premium Fast & Furious','Hot Wheels','Xe bạc, mâm bạc, bộ Premium Fast & Furious kỷ niệm 25 năm, card 2/5. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/mercedes-500-sel.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='mercedes-500-sel' OR upper(sku)='HH-HW-000009' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Mercedes-Benz 500 SEL Premium Fast & Furious'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'fast-furious-5','HH-HW-000010','Fast & Furious 5-Pack JDR19','Hot Wheels','Bộ 5 xe: Plymouth Barracuda xanh ngọc, Dodge Charger đen, Chevrolet Impala tím, Nissan Silvia vàng và Porsche 911 GT3 RS xanh lá. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/fast-furious-5.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='fast-furious-5' OR upper(sku)='HH-HW-000010' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Fast & Furious 5-Pack JDR19'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'porsche-911-rallye','HH-HW-000011','Porsche 911 Rallye xanh lá Safari Mode','Hot Wheels','Mainline xanh lá, số 17, giá nóc, mâm viền vàng, Safari Mode 2/5, card 154/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/porsche-911-rallye.webp',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='porsche-911-rallye' OR upper(sku)='HH-HW-000011' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Porsche 911 Rallye xanh lá Safari Mode'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'ford-police-interceptor','HH-MB-000012','Ford Police Interceptor Security','Matchbox','Xe đen, họa tiết SECURITY, số 26, mâm đen bạc, card 88/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/ford-police-interceptor.webp',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='ford-police-interceptor' OR upper(sku)='HH-MB-000012' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('Ford Police Interceptor Security'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'bmw-7-series','HH-MB-000013','2024 BMW 7-Series xanh dương','Matchbox','Thân xanh dương, mâm bạc nhiều chấu, card 96/125. Ảnh tham khảo xe ngoài vỉ, sản phẩm của shop đóng vỉ như ảnh đã cung cấp. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/bmw-7-series.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='bmw-7-series' OR upper(sku)='HH-MB-000013' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('2024 BMW 7-Series xanh dương'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'ferrari-sf90','HH-HW-000014','Ferrari SF90 Stradale xanh dương','Hot Wheels','Xe xanh dương, mâm đen, Ferrari 1/5, card 41/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/ferrari-sf90.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='ferrari-sf90' OR upper(sku)='HH-HW-000014' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Ferrari SF90 Stradale xanh dương'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'kick-sauber-f1','HH-HW-000015','Kick Sauber F1 Team','Hot Wheels','Xe đua đen xanh lá, viền mâm xanh lá, Formula 1 4/5, card 154/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/kick-sauber-f1.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='kick-sauber-f1' OR upper(sku)='HH-HW-000015' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Kick Sauber F1 Team'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'aston-martin-f1','HH-HW-000016','Aston Martin Aramco Formula One Team','Hot Wheels','Xe đua xanh lá, viền mâm trắng, Formula 1 5/5, card 185/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/aston-martin-f1.jpg',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='aston-martin-f1' OR upper(sku)='HH-HW-000016' OR (brand='Hot Wheels' AND lower(trim(name))=lower(trim('Aston Martin Aramco Formula One Team'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'porsche-914','HH-MB-000017','1971 Porsche 914 đỏ','Matchbox','Xe đỏ, mâm bạc, mui đen, card 95/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/porsche-914.webp',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='porsche-914' OR upper(sku)='HH-MB-000017' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('1971 Porsche 914 đỏ'))));
--> statement-breakpoint
INSERT OR IGNORE INTO products (id,sku,name,brand,description,image,price,stock,visible) SELECT 'aston-martin-vanquish','HH-MB-000018','2025 Aston Martin Vanquish xanh lá','Matchbox','Xe xanh lá ánh kim, mâm vàng nhiều chấu, card 90/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/aston-martin-vanquish.webp',NULL,NULL,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE id='aston-martin-vanquish' OR upper(sku)='HH-MB-000018' OR (brand='Matchbox' AND lower(trim(name))=lower(trim('2025 Aston Martin Vanquish xanh lá'))));
