INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('civic-eg','HH-HW-000001','92 Honda Civic EG','Hot Wheels','Mẫu tham khảo: thân xanh, họa tiết vàng. Liên hệ để xác nhận tình trạng card.','/products/civic-eg.jpg',120000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('honda-del-sol','HH-HW-000002','[Premium] Honda del Sol','Hot Wheels','Mẫu tham khảo: màu trắng, đóng vỉ. Tình trạng và phiên bản cần xác nhận.','/products/honda-del-sol.jpg',250000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('porsche-rally','HH-MB-000007','1985 Porsche 911 Rally','Matchbox','Mẫu tham khảo: màu xám, phụ kiện trên nóc, đóng vỉ.','/products/display/BCDEB870-7F5D-40D9-8979-F57762298BE3_1_105_c.jpeg',100000,2,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('porsche-918','HH-MB-000008','Porsche 918 Spyder','Matchbox','Mẫu tham khảo: màu xanh, đóng vỉ. Liên hệ để xác nhận sản phẩm.','',100000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('ferrari-dino-206','HH-HW-000003','Ferrari Dino 206 GT','Hot Wheels','Ferrari Dino 206 GT màu đỏ, mâm bạc, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-dino-206.jpg',100000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('ferrari-12cilindri','HH-HW-000004','Ferrari 12Cilindri','Hot Wheels','Ferrari 12Cilindri màu xanh, nóc đen, mâm đen trắng, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-12cilindri.jpg',100000,2,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('ferrari-f2004','HH-HW-000005','Ferrari F2004','Hot Wheels','HW Starting Grid: xe đua Ferrari F2004 màu đỏ, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/ferrari-f2004.jpg',100000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('racing-bulls-f1','HH-HW-000006','Visa Cash App Racing Bulls F1','Hot Wheels','Formula 1: xe trắng xanh, viền mâm xanh, đóng vỉ. Ảnh tham khảo theo phiên bản, tình trạng thực tế được shop xác nhận khi chốt đơn.','/products/racing-bulls-f1.jpg',120000,1,1,0) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('mercedes-500-sel','HH-HW-000009','Mercedes-Benz 500 SEL Premium Fast & Furious','Hot Wheels','Xe bạc, mâm bạc, bộ Premium Fast & Furious kỷ niệm 25 năm, card 2/5. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/mercedes-500-sel.jpg',250000,1,1,1791009281210) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('fast-furious-5','HH-HW-000010','Fast & Furious 5-Pack JDR19','Hot Wheels','Bộ 5 xe: Plymouth Barracuda xanh ngọc, Dodge Charger đen, Chevrolet Impala tím, Nissan Silvia vàng và Porsche 911 GT3 RS xanh lá. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/fast-furious-5.jpg',350000,1,1,1791009271092) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('porsche-911-rallye','HH-HW-000011','Porsche 911 Rallye xanh lá Safari Mode','Hot Wheels','Mainline xanh lá, số 17, giá nóc, mâm viền vàng, Safari Mode 2/5, card 154/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/porsche-911-rallye.webp',120000,1,1,1791009252823) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('ford-police-interceptor','HH-MB-000012','Ford Police Interceptor Security','Matchbox','Xe đen, họa tiết SECURITY, số 26, mâm đen bạc, card 88/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/ford-police-interceptor.webp',100000,1,1,1791009261639) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('bmw-7-series','HH-MB-000013','2024 BMW 7-Series xanh dương','Matchbox','Thân xanh dương, mâm bạc nhiều chấu, card 96/125. Ảnh tham khảo xe ngoài vỉ, sản phẩm của shop đóng vỉ như ảnh đã cung cấp. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/bmw-7-series.jpg',90000,1,1,1791009239859) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('ferrari-sf90','HH-HW-000014','Ferrari SF90 Stradale xanh dương','Hot Wheels','Xe xanh dương, mâm đen, Ferrari 1/5, card 41/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/ferrari-sf90.jpg',150000,1,1,1791009228922) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('kick-sauber-f1','HH-HW-000015','Kick Sauber F1 Team','Hot Wheels','Xe đua đen xanh lá, viền mâm xanh lá, Formula 1 4/5, card 154/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/kick-sauber-f1.jpg',100000,1,1,1791009218376) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('aston-martin-f1','HH-HW-000016','Aston Martin Aramco Formula One Team','Hot Wheels','Xe đua xanh lá, viền mâm trắng, Formula 1 5/5, card 185/250. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/aston-martin-f1.jpg',100000,1,1,1791009204995) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('porsche-914','HH-MB-000017','1971 Porsche 914 đỏ','Matchbox','Xe đỏ, mâm bạc, mui đen, card 95/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/porsche-914.webp',100000,2,1,1791009187841) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('aston-martin-vanquish','HH-MB-000018','2025 Aston Martin Vanquish xanh lá','Matchbox','Xe xanh lá ánh kim, mâm vàng nhiều chấu, card 90/125. Shop xác nhận tình trạng thực tế khi chốt đơn.','/products/aston-martin-vanquish.webp',100000,1,1,1791009176300) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('mclaren-f1-gt','HH-MB-000019','1997 McLaren F1 GT xanh đậm','Matchbox','Xe xanh đậm, card 32/125.','/products/display/174DA5FD-FF90-4B0A-9F1B-C4401ECB388F_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('mercedes-230-sl','HH-MB-000020','1963 Mercedes-Benz 230 SL xanh dương','Matchbox','Xe mui trần xanh dương, card 55/125.','/products/display/FE9D91E3-5649-43E7-9BB6-B20267F59922_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('lamborghini-lm002','HH-MB-000021','Lamborghini LM002 trắng','Matchbox','Xe trắng, card 87/125.','/products/display/23CF6D1C-4EEF-469C-9AB1-4F7C70DFAF55_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('honda-city-turbo-ii','HH-HW-000022','85 Honda City Turbo II trắng','Hot Wheels','Xe trắng sọc đỏ/đen, Compact Kings 4/10.','/products/display/6507DF68-2EA3-412E-AB74-12613DA54872_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('datsun-240z','HH-HW-000023','Datsun 240Z xanh lá số 23','Hot Wheels','Xe xanh lá số23, Then and Now 2/10.','/products/display/A6D5928C-7FFC-47B1-9C65-99D2010900FC_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('screamliner','HH-HW-000024','Screamliner xanh dương','Hot Wheels','Xe xanh dương số9, Rod Squad 5/10.','/products/display/E8132C63-F552-40F4-A7A5-0D7F283B0F63_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('bully-goat','HH-HW-000025','Bully Goat đỏ','Hot Wheels','Xe đỏ họa tiết sét, HW Torque 3/10.','/products/display/DCA4B074-AAEA-42A4-8824-FFDACC4A7DD0_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('dodge-charger-tooned','HH-HW-000026','70 Dodge Charger Tooned trắng','Hot Wheels','Xe Tooned trắng sọc đỏ/xanh, Tooned 4/5.','/products/display/EC7019B8-E67F-4F26-9B72-7668E44DC26F_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('maserati-tipo-61-black','HH-HW-000027','Maserati Tipo 61 đen','Hot Wheels','Xe đen số25, card 123/250, 2026.','/products/display/F1224C1D-00F9-439D-838B-B34380F2EAD0_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO products (id,sku,name,brand,description,image,price,stock,visible,updated_at) VALUES ('maserati-tipo-61-white','HH-HW-000028','Maserati Tipo 61 trắng','Hot Wheels','Xe trắng số25, card 123/250, 2026.','/products/display/5796B11E-F3BE-479E-9BEB-341EC53FCD0B_1_105_c.jpeg',NULL,NULL,1,1791009899525) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,brand=excluded.brand,description=excluded.description,image=excluded.image,price=excluded.price,stock=excluded.stock,visible=excluded.visible,updated_at=excluded.updated_at;
