import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const load=async file=>import(`data:text/javascript;base64,${Buffer.from(ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`);
const sql=await load('lib/admin-auth-sql.ts');
const crypt=await load('lib/otp-crypto.ts');
const email='taanhluan@gmail.com',user='owner',challenge='challenge',hash='hash',now=10000;
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('drizzle/0000_light_ben_urich.sql','utf8'));db.exec(readFileSync('drizzle/0001_legal_sabra.sql','utf8'));db.exec(readFileSync('drizzle/0002_magical_sauron.sql','utf8'));return db;}
function reserve(db,time=now,id=challenge){return db.prepare(sql.reserveChallenge).get(email,user,id,hash,time+600,time+60,time,time-3600,time-3600,time,time-3600);}
function ready(db){reserve(db);db.prepare('UPDATE admin_challenges SET consumed=0').run();}
function attempt(db,time=now,who=user,id=challenge){return db.prepare(sql.attemptChallenge).get(email,who,id,time);}
function verify(db,token){db.exec('BEGIN');try{const args=[email,user,challenge,hash,now];const a=db.prepare(sql.createSession).run(token,now+28800,...args);const b=db.prepare(sql.consumeChallenge).run(...args);db.exec('COMMIT');return [a.changes,b.changes];}catch(e){db.exec('ROLLBACK');throw e;}}
test('email pending delivery cannot be verified; unknown user/browser denied',()=>{const db=fixture();reserve(db);assert.equal(attempt(db),undefined);db.prepare('UPDATE admin_challenges SET consumed=0').run();assert.equal(attempt(db,now,'intruder'),undefined);assert.equal(attempt(db,now,user,'other-browser'),undefined);assert.equal(attempt(db).code_hash,hash);db.close();});
test('OTP expires exactly at ten minutes',()=>{const db=fixture();ready(db);assert.equal(attempt(db,now+600),undefined);assert.deepEqual(verifyAtExpiry(db),[0,0]);db.close();});
function verifyAtExpiry(db){const args=[email,user,challenge,hash,now+600];return [db.prepare(sql.createSession).run('token',now+28800,...args).changes,db.prepare(sql.consumeChallenge).run(...args).changes];}
test('only five attempts permitted even if code is subsequently correct',()=>{const db=fixture();ready(db);for(let i=0;i<5;i++)assert.ok(attempt(db));assert.equal(attempt(db),undefined);db.close();});
test('OTP creates one session; replay cannot create another',()=>{const db=fixture();ready(db);assert.ok(attempt(db));assert.deepEqual(verify(db,'first'),[1,1]);assert.deepEqual(verify(db,'replay'),[0,0]);assert.equal(attempt(db),undefined);assert.equal(db.prepare('SELECT COUNT(*) n FROM admin_sessions').get().n,1);assert.equal(db.prepare('SELECT * FROM admin_sessions WHERE token_hash=? AND user_id=? AND expires_at>?').get('first','other',now),undefined);assert.equal(db.prepare('SELECT * FROM admin_sessions WHERE token_hash=? AND expires_at>?').get('first',now+28800),undefined);db.close();});
test('resend enforces cooldown and five sends/hour; invalidates old challenge',()=>{const db=fixture();assert.ok(reserve(db));assert.equal(reserve(db,now+59),undefined);for(let i=1;i<5;i++)assert.ok(reserve(db,now+i*60,`new-${i}`));assert.equal(reserve(db,now+300),undefined);assert.ok(reserve(db,now+3600,'reset'));db.prepare('UPDATE admin_challenges SET consumed=0').run();assert.equal(attempt(db,now+3600,user,challenge),undefined);assert.equal(db.prepare('SELECT send_count FROM admin_challenges').get().send_count,1);db.close();});
test('crypto: six-digit codes, strong opaque tokens, context-bound HMAC',async()=>{for(let i=0;i<1000;i++){assert.match(crypt.randomCode(),/^\d{6}$/);assert.match(crypt.randomToken(),/^[a-f0-9]{64}$/);}const secret=crypt.randomToken();const a=await crypt.codeDigest(secret,'a','123456');assert.equal(a,await crypt.codeDigest(secret,'a','123456'));assert.notEqual(a,await crypt.codeDigest(secret,'b','123456'));assert.notEqual(a,await crypt.codeDigest(secret,'a','123457'));assert.notEqual(a,await crypt.codeDigest('other','a','123456'));assert.notEqual(await crypt.digest('one'),await crypt.digest('two'));});
const images=await load('lib/image-validation.ts');
test('image validator accepts existing JPEG/PNG assets and rejects truncated/polyglot files',()=>{for(const file of ['public/garage-background.jpg','public/huppo-emblem.png']){const bytes=new Uint8Array(readFileSync(file));assert.ok(images.inspectImage(bytes));assert.equal(images.inspectImage(bytes.slice(0,20)),null);const appended=new Uint8Array(bytes.length+8);appended.set(bytes);appended.set(new TextEncoder().encode('<script>'),bytes.length);assert.equal(images.inspectImage(appended),null);}});
test('image parser remains bounded and does not throw on randomized malformed bytes',()=>{for(let i=0;i<2000;i++){const bytes=crypto.getRandomValues(new Uint8Array(i%200));if(i%3===0&&bytes.length>=4)bytes.set([137,80,78,71]);if(i%3===1&&bytes.length>=4){bytes.set([255,216,255]);bytes[bytes.length-2]=255;bytes[bytes.length-1]=217;}assert.doesNotThrow(()=>images.inspectImage(bytes));}});
