import test from 'node:test';
import assert from 'node:assert/strict';
import {harness} from './route-harness.mjs';
import {createHash} from 'node:crypto';
const routes={send:'app/api/admin/otp/send/route.ts',verify:'app/api/admin/otp/verify/route.ts',products:'app/api/products/route.ts',upload:'app/api/upload/route.ts',logout:'app/api/admin/logout/route.ts',image:'app/api/images/[key]/route.ts'};
const json=body=>({body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});
const hash=token=>createHash('sha256').update(token).digest('hex');
function session(h,{user='owner',email='taanhluan@gmail.com',expiry=Math.floor(Date.now()/1000)+3600}={}){const token=crypto.randomUUID().replaceAll('-','').repeat(2);h.sqlite.prepare('INSERT INTO admin_sessions VALUES (?,?,?,?)').run(hash(token),email,user,expiry);return `huppo_admin_session=${token}`;}
async function withHarness(run){const h=await harness();try{await run(h)}finally{h.close()}}
async function issue(h){const response=await h.call(routes.send);assert.equal(response.status,200);return {cookie:response.headers.get('set-cookie').split(';')[0],code:h.mail.at(-1).text.match(/\d{6}/)[0]};}
test('all management writes reject unauthenticated and wrong-email callers',()=>withHarness(async h=>{for(const [file,method] of [[routes.products,'PUT'],[routes.upload,'POST'],[routes.send,'POST'],[routes.verify,'POST']])for(const identity of [{user:null},{email:'intruder@example.test'}])assert.equal((await h.call(file,method,{...identity,...json({code:'123456'})})).status,403);}));
test('guessed, malformed, expired and other-user sessions cannot upload or edit',()=>withHarness(async h=>{const cookies=['huppo_admin_session=evil','huppo_admin_session='+'a'.repeat(64),session(h,{expiry:1}),session(h,{user:'other'}),session(h,{email:'other@example.test'})];for(const cookie of cookies)for(const file of [routes.upload,routes.products])assert.equal((await h.call(file,file===routes.products?'PUT':'POST',{cookie,...json({})})).status,403);}));
test('CSRF rejects missing/null/cross-origin across sensitive endpoints',()=>withHarness(async h=>{const cookie=session(h);for(const origin of [null,'null','https://evil.example.test','https://shop.example.test.evil.test'])for(const file of [routes.send,routes.verify,routes.logout,routes.products,routes.upload])assert.equal((await h.call(file,file===routes.products?'PUT':'POST',{cookie,origin,...json({code:'123456'})})).status,403);assert.equal(h.mail.length,0);}));
test('OTP sends only to fixed recipient, cookie flags; one-use and logout revocation',()=>withHarness(async h=>{const {cookie,code}=await issue(h);assert.deepEqual(h.mail[0].to,['taanhluan@gmail.com']);let response=await h.call(routes.verify,'POST',{cookie,...json({code})});assert.equal(response.status,200);const setCookies=response.headers.getSetCookie();const adminCookie=setCookies.find(c=>c.startsWith('huppo_admin_session='));assert.match(adminCookie,/HttpOnly/);assert.match(adminCookie,/SameSite=Strict/);assert.match(adminCookie,/Secure/);assert.match(adminCookie,/Max-Age=28800/);assert.equal((await h.call(routes.verify,'POST',{cookie,...json({code})})).status,400);const active=adminCookie.split(';')[0];assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM admin_sessions').get().n,1);response=await h.call(routes.logout,'POST',{cookie:active});assert.equal(response.status,200);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM admin_sessions').get().n,0);assert.equal((await h.call(routes.upload,'POST',{cookie:active})).status,403);}));
test('parallel OTP verification creates at most one session',()=>withHarness(async h=>{const {cookie,code}=await issue(h);const result=await Promise.all(Array.from({length:5},()=>h.call(routes.verify,'POST',{cookie,...json({code})})));assert.equal(result.filter(r=>r.status===200).length,1);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM admin_sessions').get().n,1);}));
test('five wrong codes exhaust challenge even when correct code follows',()=>withHarness(async h=>{const {cookie,code}=await issue(h);const wrong=code==='000000'?'111111':'000000';for(let i=0;i<5;i++)assert.equal((await h.call(routes.verify,'POST',{cookie,...json({code:wrong})})).status,400);assert.equal((await h.call(routes.verify,'POST',{cookie,...json({code})})).status,400);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM admin_sessions').get().n,0);}));
test('resend race is throttled and emits only one provider request',()=>withHarness(async h=>{const response=await Promise.all(Array.from({length:4},()=>h.call(routes.send)));assert.equal(response.filter(r=>r.status===200).length,1);assert.equal(response.filter(r=>r.status===429).length,3);assert.equal(h.mail.length,1);for(const r of response.filter(r=>r.status===429))assert.ok(Number(r.headers.get('retry-after'))>0);}));
test('invalid OTP JSON never authenticates or throws',()=>withHarness(async h=>{for(const body of ['null','[]','{bad',JSON.stringify({code:123456}),JSON.stringify({code:'1234567'}),JSON.stringify({code:'１２３４５６'})])assert.equal((await h.call(routes.verify,'POST',{body,headers:{'Content-Type':'application/json'}})).status,400);}));
test('product validation prevents remote/active image sources and invalid values',()=>withHarness(async h=>{const cookie=session(h),product={id:'test-only',name:'Fixture',brand:'Hot Wheels',description:'',image:'',price:100,stock:2,visible:false};for(const patch of [{id:"x'; DROP TABLE products;--"},{image:'javascript:alert(1)'},{image:'https://evil.test/image.png'},{image:'/api/images/../../.env.local'},{price:-1},{stock:1.5},{visible:'true'}])assert.equal((await h.call(routes.products,'PUT',{cookie,...json({...product,...patch})})).status,400);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM products').get().n,0);}));
test('upload rejects SVG, HTML and fake MIME; no writes for rejected content',()=>withHarness(async h=>{const cookie=session(h);for(const content of ['<svg onload="alert(1)"></svg>','<html><script>alert(1)</script></html>']){const form=new FormData();form.append('file',new File([content],'photo.png',{type:'image/png'}));assert.equal((await h.call(routes.upload,'POST',{cookie,body:form})).status,400);}assert.equal(h.files.size,0);}));
test('upload rejects PNG magic-only file masquerading as a real image',()=>withHarness(async h=>{const form=new FormData();form.append('file',new File([new Uint8Array([137,80,78,71])],'<script>.png',{type:'image/png'}));assert.equal((await h.call(routes.upload,'POST',{cookie:session(h),body:form})).status,400);assert.equal(h.files.size,0);}));
test('public image reads reject traversal and do not expose errors',()=>withHarness(async h=>{for(const key of ['../../.env.local','a/b','<svg>','%2e%2e'])assert.equal((await h.call(routes.image,'GET',{params:{key}})).status,404);}));
test('actual streamed byte limits reject large JSON even without Content-Length',()=>withHarness(async h=>{const cookie=session(h);assert.equal((await h.call(routes.verify,'POST',{body:' '.repeat(1025),headers:{'Content-Type':'application/json'}})).status,413);assert.equal((await h.call(routes.products,'PUT',{cookie,body:' '.repeat(16385),headers:{'Content-Type':'application/json'}})).status,413);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM products').get().n,0);}));
test('multipart streamed byte limit cannot be bypassed by tiny Content-Length',()=>withHarness(async h=>{const cookie=session(h);assert.equal((await h.call(routes.upload,'POST',{cookie,body:new Uint8Array(6*1024*1024+1),headers:{'Content-Type':'multipart/form-data; boundary=x','Content-Length':'1'}})).status,413);assert.equal(h.files.size,0);}));
test('valid product persists safely, SQL payload remains data, hidden item stays private',()=>withHarness(async h=>{const cookie=session(h),name="x'); DROP TABLE products;--",product={id:'fixture-only',name,brand:'Hot Wheels',description:'<script>alert(1)</script>',image:'',price:50000,stock:2,visible:false};assert.equal((await h.call(routes.products,'PUT',{cookie,...json(product)})).status,200);const row=h.sqlite.prepare('SELECT * FROM products WHERE id=?').get(product.id);assert.equal(row.description,product.description);const publicList=await(await h.call(routes.products,'GET',{user:null})).json();assert.equal(publicList.some(p=>p.id===product.id),false);}));
test('valid PNG is stored under random safe name and served nosniff image MIME',()=>withHarness(async h=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j9aIAAAAASUVORK5CYII=','base64'),form=new FormData();form.append('file',new File([png],'../../malicious.svg',{type:'application/octet-stream'}));const response=await h.call(routes.upload,'POST',{cookie:session(h),body:form});assert.equal(response.status,200);const {url}=await response.json();assert.match(url,/^\/api\/images\/[a-f0-9-]{36}\.png$/);const image=await h.call(routes.image,'GET',{params:{key:url.split('/').at(-1)}});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.equal(image.headers.get('x-content-type-options'),'nosniff');}));
test('provider failure never activates a pending code',()=>withHarness(async h=>{h.env.RESEND_API_KEY='provider-failure';const response=await h.call(routes.send);assert.equal(response.status,503);assert.equal(response.headers.get('set-cookie'),null);assert.equal(h.sqlite.prepare('SELECT consumed FROM admin_challenges').get().consumed,1);}));
test('SKU normalizes, remains stable on legacy edits, rejects duplicate SKU and same variant',()=>withHarness(async h=>{
 const cookie=session(h),product={id:'code-test',sku:'  hh-hw-test001  ',name:'SKU fixture',brand:'Hot Wheels',description:'',image:'',price:50000,stock:2,visible:false};
 let response=await h.call(routes.products,'PUT',{cookie,...json(product)});assert.equal(response.status,200);assert.equal((await response.json()).sku,'HH-HW-TEST001');
 for(const patch of [{id:'duplicate-code',sku:'hh-hw-test001',name:'Different name'},{id:'duplicate-name',sku:'HH-HW-TEST002'}])assert.equal((await h.call(routes.products,'PUT',{cookie,...json({...product,...patch})})).status,409);
 const {sku,...legacy}=product;response=await h.call(routes.products,'PUT',{cookie,...json({...legacy,stock:1})});assert.equal(response.status,200);assert.equal((await response.json()).sku,'HH-HW-TEST001');
 assert.equal(h.sqlite.prepare('SELECT stock FROM products WHERE id=?').get(product.id).stock,1);
 assert.throws(()=>h.sqlite.prepare('INSERT INTO products (id,sku,name,brand) VALUES (?,?,?,?)').run('raw-duplicate','hh-hw-test001','Raw duplicate','Hot Wheels'),/UNIQUE constraint/);
}));
test('new products without SKU receive a unique searchable shop code',()=>withHarness(async h=>{
 const cookie=session(h),product={id:'generated-code',name:'New Matchbox variant',brand:'Matchbox',description:'',image:'',price:null,stock:null,visible:false};
 const response=await h.call(routes.products,'PUT',{cookie,...json(product)});assert.equal(response.status,200);assert.match((await response.json()).sku,/^HH-MB-[A-F0-9]{8}$/);
}));
test('catalog puts the most recently saved product first while preserving inventory',()=>withHarness(async h=>{
 const cookie=session(h),base={sku:'HH-HW-RECENT',name:'Recent fixture',brand:'Hot Wheels',description:'',image:'',price:123000,stock:3,visible:true};
 h.sqlite.prepare('INSERT INTO products (id,sku,name,brand,price,stock,visible,updated_at) VALUES (?,?,?,?,?,?,?,?)').run('older','HH-HW-OLDER','Older fixture','Hot Wheels',99000,2,1,10);
 const save=await h.call(routes.products,'PUT',{cookie,...json({...base,id:'recent'})});assert.equal(save.status,200);assert.ok((await save.json()).updated_at>10);
 let list=await(await h.call(routes.products,'GET',{user:null})).json();assert.deepEqual(Array.from(list,p=>p.id),['recent','older']);
 await h.call(routes.products,'PUT',{cookie,...json({...base,id:'older',sku:'HH-HW-OLDER',name:'Older fixture'})});
 h.sqlite.prepare('UPDATE products SET updated_at=updated_at+1 WHERE id=?').run('older');
 list=await(await h.call(routes.products,'GET',{user:null})).json();assert.equal(list[0].id,'older');assert.equal(list[0].stock,3);assert.equal(list[0].price,123000);
}));
